# Copyright 2022 The kpt Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ServiceAccount
apiVersion: v1
metadata:
  name: porch-server
  namespace: porch-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: porch-server
  namespace: porch-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: porch-server
  template:
    metadata:
      labels:
        app: porch-server
    spec:
      serviceAccountName: porch-server
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: webhook-certs
          emptyDir: {}
        - name: api-server-certs
          emptyDir: {}
      containers:
        - name: porch-server
          # Update image to the image of your porch apiserver build.
          image: gcr.io/example-google-project-id/porch-server:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
          volumeMounts:
            - mountPath: /cache
              name: cache-volume
            - mountPath: /etc/webhook/certs
              name: webhook-certs
            - name: api-server-certs
              mountPath: /tmp/certs
          env:
          # Uncomment to enable trace-reporting to jaeger
          #- name: OTEL
          #  value: otel://jaeger-oltp:4317
          - name: OTEL_SERVICE_NAME
            value: porch-server
          - name: CERT_STORAGE_DIR
            value: "/etc/webhook/certs"
          args:
            - --function-runner=function-runner:9445
            - --cache-directory=/cache
            - --cert-dir=/tmp/certs
            - --secure-port=4443
            - --repo-sync-frequency=60s

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: porch-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 4443
      name: api
    - port: 8443
      protocol: TCP
      targetPort: 8443
      name: webhooks
  selector:
    app: porch-server
