#!/bin/bash

# Copyright 2024 The kpt Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

if [[ -z "${OUTDIR:-}" ]]; then
    echo "Must specify OUTDIR"
    exit 1
fi

for podname in $(kubectl get pods -n porch-system -o custom-columns=NAME:.metadata.name --no-headers=true); do
  mkdir -p ${OUTDIR}/pods/porch-system/
  kubectl -n porch-system logs ${podname} > ${OUTDIR}/pods/porch-system/${podname}.log
done        
