definitions:
  Function:
    properties:
      ConfigMap:
        additionalProperties:
          type: string
        description: '`ConfigMap` is a convenient way to specify a function config
          of kind ConfigMap.'
        type: object
      ConfigPath:
        description: |-
          `ConfigPath` specifies a slash-delimited relative path to a file in the current directory
          containing a KRM resource used as the function config. This resource is
          excluded when resolving 'sources', and as a result cannot be operated on
          by the pipeline.
        type: string
      Image:
        description: |-
          `Image` specifies the function container image.
          It can either be fully qualified, e.g.:

          image: gcr.io/kpt-fn/set-labels

          Optionally, kpt can be configured to use a image
          registry host-path that will be used to resolve the image path in case
          the image path is missing (Defaults to gcr.io/kpt-fn).
          e.g. The following resolves to gcr.io/kpt-fn/set-labels:

          image: set-labels
        type: string
    title: Function specifies a KRM function.
    type: object
    x-go-package: github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1
  Git:
    properties:
      Directory:
        description: |-
          Directory is the sub directory of the git repository.
          e.g. 'staging/cockroachdb'
        type: string
      Ref:
        description: Ref can be a Git branch, tag, or a commit SHA-1.
        type: string
      Repo:
        description: |-
          Repo is the git repository the package.
          e.g. 'https://github.com/kubernetes/examples.git'
        type: string
    title: Git is the user-specified locator for a package on Git.
    type: object
    x-go-package: github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1
  GitLock:
    properties:
      Commit:
        description: |-
          Commit is the SHA-1 for the last fetch of the package.
          This is set by kpt for bookkeeping purposes.
        type: string
      Directory:
        description: |-
          Directory is the sub directory of the git repository that was fetched.
          e.g. 'staging/cockroachdb'
        type: string
      Ref:
        description: |-
          Ref can be a Git branch, tag, or a commit SHA-1 that was fetched.
          e.g. 'master'
        type: string
      Repo:
        description: |-
          Repo is the git repository that was fetched.
          e.g. 'https://github.com/kubernetes/examples.git'
        type: string
    title: GitLock is the resolved locator for a package on Git.
    type: object
    x-go-package: github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1
  Inventory:
    description: All of the the parameters are required if any are set.
    properties:
      Annotations:
        additionalProperties:
          type: string
        type: object
      InventoryID:
        description: Unique label to identify inventory resource in cluster.
        type: string
      Labels:
        additionalProperties:
          type: string
        type: object
      Name:
        description: Name of the inventory resource.
        type: string
      Namespace:
        description: Namespace for the inventory resource.
        type: string
    title: Inventory encapsulates the parameters for the inventory resource applied
      to a cluster.
    type: object
    x-go-package: github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1
  NameMeta:
    properties:
      name:
        description: Name is the metadata.name field of a Resource
        type: string
        x-go-name: Name
      namespace:
        description: Namespace is the metadata.namespace field of a Resource
        type: string
        x-go-name: Namespace
    title: NameMeta contains name information.
    type: object
    x-go-package: sigs.k8s.io/kustomize/kyaml/yaml
  ObjectMeta:
    description: ObjectMeta contains metadata about a Resource
    properties:
      annotations:
        additionalProperties:
          type: string
        description: Annotations is the metadata.annotations field of a Resource.
        type: object
        x-go-name: Annotations
      labels:
        additionalProperties:
          type: string
        description: Labels is the metadata.labels field of a Resource
        type: object
        x-go-name: Labels
      name:
        description: Name is the metadata.name field of a Resource
        type: string
        x-go-name: Name
      namespace:
        description: Namespace is the metadata.namespace field of a Resource
        type: string
        x-go-name: Namespace
    type: object
    x-go-package: sigs.k8s.io/kustomize/kyaml/yaml
  OriginType:
    title: OriginType defines the type of origin for a package.
    type: string
    x-go-package: github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1
  PackageInfo:
    description: |-
      These fields are not consumed by any functionality in kpt and are simply passed through.
      Note that like any other KRM resource, humans and automation can also use `metadata.labels` and
      `metadata.annotations` as the extension mechanism.
    properties:
      Description:
        description: Description contains a short description of the package.
        type: string
      Emails:
        description: Email is the list of emails for the package authors.
        items:
          type: string
        type: array
      Keywords:
        description: Keywords is a list of keywords for this package.
        items:
          type: string
        type: array
      License:
        description: 'SPDX license identifier (e.g. "Apache-2.0"). See: https://spdx.org/licenses/'
        type: string
      LicenseFile:
        description: Relative slash-delimited path to the license file (e.g. LICENSE.txt)
        type: string
      Man:
        description: Man is the path to documentation about the package
        type: string
      Site:
        description: Site is the URL for package web page.
        type: string
    title: PackageInfo contains optional information about the package such as license,
      documentation, etc.
    type: object
    x-go-package: github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1
  Pipeline:
    properties:
      Mutators:
        description: Mutators defines a list of of KRM functions that mutate resources.
        items:
          $ref: '#/definitions/Function'
        type: array
      Validators:
        description: |-
          Validators defines a list of KRM functions that validate resources.
          Validators are not permitted to mutate resources.
        items:
          $ref: '#/definitions/Function'
        type: array
    title: Pipeline declares a pipeline of functions used to mutate or validate resources.
    type: object
    x-go-package: github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1
  ResourceMeta:
    properties:
      annotations:
        additionalProperties:
          type: string
        description: Annotations is the metadata.annotations field of a Resource.
        type: object
        x-go-name: Annotations
      apiVersion:
        description: APIVersion is the apiVersion field of a Resource
        type: string
        x-go-name: APIVersion
      kind:
        description: Kind is the kind field of a Resource
        type: string
        x-go-name: Kind
      labels:
        additionalProperties:
          type: string
        description: Labels is the metadata.labels field of a Resource
        type: object
        x-go-name: Labels
      name:
        description: Name is the metadata.name field of a Resource
        type: string
        x-go-name: Name
      namespace:
        description: Namespace is the metadata.namespace field of a Resource
        type: string
        x-go-name: Namespace
    title: ResourceMeta contains the metadata for a both Resource Type and Resource.
    type: object
    x-go-package: sigs.k8s.io/kustomize/kyaml/yaml
  TypeMeta:
    description: |-
      TypeMeta partially copies apimachinery/pkg/apis/meta/v1.TypeMeta
      No need for a direct dependence; the fields are stable.
    properties:
      apiVersion:
        description: APIVersion is the apiVersion field of a Resource
        type: string
        x-go-name: APIVersion
      kind:
        description: Kind is the kind field of a Resource
        type: string
        x-go-name: Kind
    type: object
    x-go-package: sigs.k8s.io/kustomize/kyaml/yaml
  UpdateStrategyType:
    title: UpdateStrategyType defines the strategy for updating a package from upstream.
    type: string
    x-go-package: github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1
  Upstream:
    properties:
      Git:
        $ref: '#/definitions/Git'
      Type:
        $ref: '#/definitions/OriginType'
      UpdateStrategy:
        $ref: '#/definitions/UpdateStrategyType'
    title: Upstream is a user-specified upstream locator for a package.
    type: object
    x-go-package: github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1
  UpstreamLock:
    properties:
      Git:
        $ref: '#/definitions/GitLock'
      Type:
        $ref: '#/definitions/OriginType'
    title: UpstreamLock is a resolved locator for the last fetch of the package.
    type: object
    x-go-package: github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1
  kptfile:
    properties:
      Info:
        $ref: '#/definitions/PackageInfo'
      Inventory:
        $ref: '#/definitions/Inventory'
      Pipeline:
        $ref: '#/definitions/Pipeline'
      Upstream:
        $ref: '#/definitions/Upstream'
      UpstreamLock:
        $ref: '#/definitions/UpstreamLock'
      annotations:
        additionalProperties:
          type: string
        description: Annotations is the metadata.annotations field of a Resource.
        type: object
        x-go-name: Annotations
      apiVersion:
        description: APIVersion is the apiVersion field of a Resource
        type: string
        x-go-name: APIVersion
      kind:
        description: Kind is the kind field of a Resource
        type: string
        x-go-name: Kind
      labels:
        additionalProperties:
          type: string
        description: Labels is the metadata.labels field of a Resource
        type: object
        x-go-name: Labels
      name:
        description: Name is the metadata.name field of a Resource
        type: string
        x-go-name: Name
      namespace:
        description: Namespace is the metadata.namespace field of a Resource
        type: string
        x-go-name: Namespace
    title: KptFile contains information about a package managed with kpt.
    type: object
    x-go-name: KptFile
    x-go-package: github.com/GoogleContainerTools/kpt/pkg/api/kptfile/v1
info:
  title: Kptfile schema.
  version: v1
paths: {}
swagger: "2.0"
