# Copyright 2026 The kpt Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
#    - funlen # TODO: fix
#    - gosec  # TODO: fix
  settings:
    dupl:
      threshold: 400
    gocyclo:
      min-complexity: 30
    lll:
      line-length: 170
    revive:
      confidence: .85
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: Using the variable on range scope `tc` in function literal
      - path: (.+)_test\.go$
        linters:
          - gosec
          - funlen
      - path: (.+)/test(.+)/(.+)\.go$ # test, testutil packages
        linters:
          - gosec
          - funlen
    paths:
      - thirdparty/
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - thirdparty/
      - third_party$
      - builtin$
      - examples$
