# Required metadata
sonar.projectKey=kptdev_kpt
sonar.projectName=kpt
sonar.organization=kptdev

sonar.language=go

# Path to your Go source code
sonar.sources=pkg, func, commands, internal, run, api

# Exclude files if needed
sonar.exclusions=**/test/**, **/examples/*, **/scripts/*, **/*_test.go, **/testing*, **/generated/**, **/testdata/**, **/*zz_generated.*

# To include test coverage reports (optional)
#sonar.tests=./
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=**/test/**, **/*_test.go, **/testing*, **/api/**
sonar.go.tests.reportPaths=report.xml
sonar.go.coverage.reportPaths=coverage.out
# To exclude duplicated blocks from CPD (Copy-Paste Detection)
sonar.cpd.exclusions=**/*_test.go, **/test/**, **/testing**, **/api/**
