apiVersion: fn.kpt.dev/v1alpha1
kind: SetLabels
metadata:
  name: mariadb
  namespace: example
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    app.kubernetes.io/name: mariadb
labels:
  app.kubernetes.io/name: mariadb
