# Copyright 2022 The kpt Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Namespace
metadata:
  name: porch-system
spec: {}

---

apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.porch.kpt.dev
spec:
  insecureSkipTLSVerify: true
  group: porch.kpt.dev
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: porch-system
    port: 9443
  version: v1alpha1

---

apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: porch-system
spec:
  type: ExternalName
  # We use Docker DNS to reach the host. See Makefile for how the containers are started on porch network
  # with `--add-host host.docker.internal:host-gateway` flag.
  externalName: host.docker.internal
