# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/${_GITHUB_USER}/kpt.git']

  - name: gcr.io/cloud-builders/git
    dir: 'kpt'
    args: ['checkout', '${TAG_NAME}']

  # Build the image that contains most of the tools we need (e.g. tar,
  # jq, gzip, golang, bash, etc.) to build kpt tarball. This image
  # (kpt-builder) is re-used on most steps.
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'kpt'
    args: ['build', '-f', '/workspace/kpt/release/Dockerfile.kpt-build', '-t', 'kpt-builder', '.']

  # run e2e tests and linting
  - name: 'kpt-builder'
    args: ['git', 'config', '--global', 'user.email', 'you@example.com']
    dir: 'kpt'
    volumes:
      - name: home
        path: /root
  - name: 'kpt-builder'
    args: ['git', 'config', '--global', 'user.name', 'Your Name']
    dir: 'kpt'
    volumes:
      - name: home
        path: /root
  - name: 'kpt-builder'
    args: ['make', 'all']
    env: ['GO111MODULE=on']
    dir: 'kpt'
    volumes:
      - name: go-modules
        path: /go
      - name: home
        path: /root

  # remove any dirty files after running the build
  - name: gcr.io/cloud-builders/git
    dir: 'kpt'
    args: ['reset', '--hard']

  # Generate and package the licenses and necessary source code.
  - name: 'kpt-builder'
    dir: 'kpt'
    args: ['bash', '/workspace/scripts/create-licenses.sh']
    volumes:
      - name: go-modules
        path: /go

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [ '-c', 'mkdir -p ~/.config/goreleaser && gcloud secrets versions access latest --secret=github-token > ~/.config/goreleaser/github_token' ]

  - name: 'goreleaser/goreleaser'
    dir: 'kpt'
    args: ['release', '--skip-validate', '-f', 'release/tag/goreleaser.yaml']

  # create a working folder for downloading release artifacts from github and pushing
  # them to GCS
  - name: 'launcher.gcr.io/google/ubuntu1604'
    entrypoint: 'bash'
    args: [ '-c', 'mkdir artifacts']

  # download release artifacts from github
  - name: 'launcher.gcr.io/google/ubuntu1604'
    dir: 'artifacts'
    args: [ 'curl', '-L',
            '-O', 'https://github.com/${_GITHUB_USER}/kpt/releases/download/${TAG_NAME}/kpt_darwin_amd64-${_VERSION}.tar.gz',
            '-O', 'https://github.com/${_GITHUB_USER}/kpt/releases/download/${TAG_NAME}/kpt_linux_amd64-${_VERSION}.tar.gz',
            '-O', 'https://github.com/${_GITHUB_USER}/kpt/releases/download/${TAG_NAME}/kpt_windows_amd64-${_VERSION}.tar.gz'
    ]

  # upload the artifacts to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'artifacts'
    args: [ 'cp', '-a', 'public-read', 'kpt_darwin_amd64-${_VERSION}.tar.gz', 'gs://${_GCS_BUCKET}/releases/${TAG_NAME}/darwin_amd64/kpt_darwin_amd64_${TAG_NAME}.tar.gz' ]

  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'artifacts'
    args: [ 'cp', '-a', 'public-read', 'kpt_darwin_amd64-${_VERSION}.tar.gz', 'gs://${_GCS_BUCKET}/latest/darwin_amd64/kpt_darwin_amd64.tar.gz' ]

  - name: 'launcher.gcr.io/google/ubuntu1604'
    dir: 'artifacts'
    entrypoint: 'bash'
    args: [ '-c', 'tar -xvf kpt_darwin_amd64-${_VERSION}.tar.gz kpt && mv kpt kpt_darwin_amd64' ]

  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'artifacts'
    args: [ 'cp', '-a', 'public-read', 'kpt_darwin_amd64', 'gs://${_GCS_BUCKET}/latest/darwin_amd64/kpt' ]

  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'artifacts'
    args: [ 'cp', '-a', 'public-read', 'kpt_linux_amd64-${_VERSION}.tar.gz', 'gs://${_GCS_BUCKET}/releases/${TAG_NAME}/linux_amd64/kpt_linux_amd64_${TAG_NAME}.tar.gz' ]

  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'artifacts'
    args: [ 'cp', '-a', 'public-read', 'kpt_linux_amd64-${_VERSION}.tar.gz', 'gs://${_GCS_BUCKET}/latest/linux_amd64/kpt_linux_amd64.tar.gz' ]

  - name: 'launcher.gcr.io/google/ubuntu1604'
    dir: 'artifacts'
    entrypoint: 'bash'
    args: [ '-c', 'tar -xvf kpt_linux_amd64-${_VERSION}.tar.gz kpt && mv kpt kpt_linux_amd64' ]

  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'artifacts'
    args: [ 'cp', '-a', 'public-read', 'kpt_linux_amd64', 'gs://${_GCS_BUCKET}/latest/linux_amd64/kpt' ]

  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'artifacts'
    args: [ 'cp', '-a', 'public-read', 'kpt_windows_amd64-${_VERSION}.tar.gz', 'gs://${_GCS_BUCKET}/releases/${TAG_NAME}/windows_amd64/kpt_windows_amd64_${TAG_NAME}.tar.gz' ]

  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'artifacts'
    args: [ 'cp', '-a', 'public-read', 'kpt_windows_amd64-${_VERSION}.tar.gz', 'gs://${_GCS_BUCKET}/latest/windows_amd64/kpt_windows_amd64.tar.gz' ]

  - name: 'launcher.gcr.io/google/ubuntu1604'
    dir: 'artifacts'
    entrypoint: 'bash'
    args: [ '-c', 'tar -xvf kpt_windows_amd64-${_VERSION}.tar.gz kpt.exe && mv kpt.exe kpt_windows_amd64.exe' ]

  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'artifacts'
    args: [ 'cp', '-a', 'public-read', 'kpt_windows_amd64.exe', 'gs://${_GCS_BUCKET}/latest/windows_amd64/kpt.exe' ]

  # build docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'kpt'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/kpt:${TAG_NAME}', '.', '--build-arg', 'KPT_VERSION=${_VERSION}']

  - name: 'gcr.io/cloud-builders/docker'
    dir: 'kpt'
    args: [ 'tag', 'gcr.io/$PROJECT_ID/kpt:${TAG_NAME}',  'gcr.io/$PROJECT_ID/kpt:latest' ]

  # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kpt:${TAG_NAME}']

  # update latest tag on release
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kpt:latest']

timeout: '60m'
