apiVersion: v1
kind: Service
metadata:
  name: ghost-app
  namespace: example
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
