FROM golang:1.21.5-alpine3.18 as builder

WORKDIR /go/src/github.com/GoogleContainerTools/kpt

# Ensure the wrapper server and grpc-health-probe is statically linked so that they works in distroless-based images.
ENV CGO_ENABLED=0

COPY go.mod go.sum ./
COPY porch/go.mod porch/go.sum porch/
COPY porch/api/go.mod porch/api/go.sum porch/api/

RUN go install github.com/grpc-ecosystem/grpc-health-probe@v0.4.11
COPY porch/func/ porch/func/
RUN cd porch/func ; go build -v -o /wrapper-server/wrapper-server ./wrapper-server
RUN cp $GOPATH/bin/grpc-health-probe /wrapper-server/

FROM alpine:3.18

COPY --from=builder /wrapper-server/* /wrapper-server/
