// Copyright 2019,2026 The kpt Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package runneroptions holds options for the function runtime
package runneroptions

import (
	"fmt"
	"net/url"
	"os"
	"strings"
)

const (
	FuncGenPkgContext = "builtins/gen-pkg-context"
	GHCRImagePrefix   = "ghcr.io/kptdev/krm-functions-catalog/"
	PrefixEnvVar      = "KPT_IMAGE_PREFIX"
)

// DefaultImagePrefix returns the image prefix from the KPT_IMAGE_PREFIX env var, or GHCRImagePrefix if unset.
func DefaultImagePrefix() string {
	if p := os.Getenv(PrefixEnvVar); p != "" {
		return p
	}
	return GHCRImagePrefix
}

type RunnerOptions struct {
	// ImagePullPolicy controls the image pulling behavior before running the container.
	ImagePullPolicy ImagePullPolicy

	// when set to true, function runner will set the package path annotation
	// on resources that do not have it set. The resources generated by
	// functions do not have this annotation set.
	SetPkgPathAnnotation bool

	DisplayResourceCount bool

	// allowExec determines if function binary executable are allowed
	// to be run during pipeline execution. Running function binaries is a
	// privileged operation, so explicit permission is required.
	AllowExec bool

	// AllowNetwork specifies if container based functions are allowed
	// to access network during pipeline execution. Accessing network is
	// considered a privileged operation (and makes render operation non-hermetic),
	// so explicit permission is desired.
	AllowNetwork bool

	// allowWasm determines if function wasm are allowed to be run during pipeline
	// execution. Running wasm function is an alpha feature, so it needs to be
	// enabled explicitly.
	AllowWasm bool

	// ImagePrefix determines the prefix ResolveToImage will use when resolving a
	// partial image reference to a fully qualified image reference
	ImagePrefix string

	ExtraTlsCerts [][]byte
}

func (opts *RunnerOptions) InitDefaults(defaultImagePrefix string) {
	opts.ImagePullPolicy = IfNotPresentPull
	opts.ImagePrefix = defaultImagePrefix
}

// ResolveToImage converts the KRM function short path to the full image url.
// If the function is a catalog function, it prepends `prefix`, e.g. "set-namespace:v0.1" --> prefix + "set-namespace:v0.1".
// A "/" is appended to `prefix` if it is not an empty string and does not end with a "/".
func (opts RunnerOptions) ResolveToImage(image string) string {
	prefix := strings.TrimRight(opts.ImagePrefix, "/")
	if prefix == "" {
		return image
	}
	if !strings.Contains(image, "/") {
		return fmt.Sprintf("%s/%s", prefix, image)
	}
	return image
}

// ValidatePrefix checks that ImagePrefix is a valid registry path.
func (opts RunnerOptions) ValidatePrefix() error {
	if opts.ImagePrefix == "" {
		return nil
	}
	prefix := strings.TrimRight(opts.ImagePrefix, "/")
	// Reject prefixes that include a URL scheme
	if strings.Contains(prefix, "://") {
		return fmt.Errorf("invalid image prefix %q: must not include a scheme (e.g. https://)", opts.ImagePrefix)
	}
	// Reject fragments and query strings
	if strings.ContainsAny(prefix, "?#") {
		return fmt.Errorf("invalid image prefix %q: must not contain '?' or '#'", opts.ImagePrefix)
	}
	// Prepend a scheme so url.Parse can validate the host/path structure
	u, err := url.Parse("https://" + prefix)
	if err != nil || u.Host == "" {
		return fmt.Errorf("invalid image prefix %q: must be a valid registry path", opts.ImagePrefix)
	}
	return nil
}

type SingleLineFormatter struct {
	Title     string   // Label for the output
	Lines     []string // Lines to be joined
	UseQuote  bool     // Whether to quote each line
	Separator string   // Separator between lines (e.g., comma, space)
}

func (sf *SingleLineFormatter) String() string {
	strInterpolator := "%s"
	if sf.UseQuote {
		strInterpolator = "%q"
	}

	var formattedLines []string
	for _, line := range sf.Lines {
		line = strings.ReplaceAll(line, "\n", " ")
		line = strings.TrimSpace(line)
		formattedLines = append(formattedLines, fmt.Sprintf(strInterpolator, line))
	}

	return fmt.Sprintf("%s: %s", sf.Title, strings.Join(formattedLines, sf.Separator))
}
