// Code generated by "stringer -type=MainBranchStrategy -linecomment"; DO NOT EDIT.

package git

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorIfMissing-0]
	_ = x[CreateIfMissing-1]
	_ = x[SkipVerification-2]
}

const _MainBranchStrategy_name = "ErrorIsMissingCreateIfMissingSkipVerification"

var _MainBranchStrategy_index = [...]uint8{0, 14, 29, 45}

func (i MainBranchStrategy) String() string {
	if i < 0 || i >= MainBranchStrategy(len(_MainBranchStrategy_index)-1) {
		return "MainBranchStrategy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MainBranchStrategy_name[_MainBranchStrategy_index[i]:_MainBranchStrategy_index[i+1]]
}
