# Copyright 2026 The kpt Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: kpt API release
on:
  push:
    tags:
    - "api/v[0-9]+.[0-9]+.[0-9]+*"

env:
  GOPATH: ${{ github.workspace }}/go

jobs:
  build:
    runs-on: ubuntu-latest
    name: kpt-api-release
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: api/go.mod
          cache-dependency-path: api/go.sum
      - name: Build, test, lint (api module)
        run: |
          git config --global user.email you@example.com
          git config --global user.name Your Name
          make api
